### ISSUE TITLE
1.0.3 doesn't seem to have "dist"

### ISSUE THREAD

**Issue by malthe** [call-a3/rollup-plugin-magic-string#41]
Compared to the 1.0.2 release, 1.0.3 doesn't have "dist/index.js" in it.

**Comment by call-a3** [comment]
Confirmed. I'll have to look into why this happened. Normally only some dependencies got upgraded, but maybe a more recent release of semantic-release doesn't include the dist folder by default anymore... Or I might have changed something else and forgot about it.
